permissions:
  fly: "OPS"
  fly_others: "OPS"
  color_chat: "NOBODY"
  spawn: "ALL"
  spawn_set: "OPS"
  spawn_others: "OPS"
  spawn_at_bed: "ALL"
  spawn_at_anchor: "ALL"
spawn:
  x: 0.0
  y: 100.0
  z: 0.0
  pitch: 0.0
  yaw: 0.0
  world: "world"