name: DarkRealms
version: ${project.version}
main: nicholasmy.darkrealms.DarkRealms
api-version: 1.16
commands:
  allow:
    description: Change permissions for DarkRealms features.
    usage: /allow <permission> <nobody|ops|all>